// Mocks generated by Mockito 5.4.6 from annotations
// in obsi/test/src/ai_assistant/openai_compatible_assistant_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:openai_dart/src/client.dart' as _i4;
import 'package:openai_dart/src/generated/client.dart' as _i7;
import 'package:openai_dart/src/generated/schema/schema.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseRequest_1 extends _i1.SmartFake implements _i2.BaseRequest {
  _FakeBaseRequest_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_2 extends _i1.SmartFake
    implements _i2.StreamedResponse {
  _FakeStreamedResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_3 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateChatCompletionResponse_4 extends _i1.SmartFake
    implements _i3.CreateChatCompletionResponse {
  _FakeCreateChatCompletionResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateCompletionResponse_5 extends _i1.SmartFake
    implements _i3.CreateCompletionResponse {
  _FakeCreateCompletionResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateEmbeddingResponse_6 extends _i1.SmartFake
    implements _i3.CreateEmbeddingResponse {
  _FakeCreateEmbeddingResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListPaginatedFineTuningJobsResponse_7 extends _i1.SmartFake
    implements _i3.ListPaginatedFineTuningJobsResponse {
  _FakeListPaginatedFineTuningJobsResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFineTuningJob_8 extends _i1.SmartFake implements _i3.FineTuningJob {
  _FakeFineTuningJob_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListFineTuningJobEventsResponse_9 extends _i1.SmartFake
    implements _i3.ListFineTuningJobEventsResponse {
  _FakeListFineTuningJobEventsResponse_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListFineTuningJobCheckpointsResponse_10 extends _i1.SmartFake
    implements _i3.ListFineTuningJobCheckpointsResponse {
  _FakeListFineTuningJobCheckpointsResponse_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeImagesResponse_11 extends _i1.SmartFake
    implements _i3.ImagesResponse {
  _FakeImagesResponse_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListModelsResponse_12 extends _i1.SmartFake
    implements _i3.ListModelsResponse {
  _FakeListModelsResponse_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeModel_13 extends _i1.SmartFake implements _i3.Model {
  _FakeModel_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteModelResponse_14 extends _i1.SmartFake
    implements _i3.DeleteModelResponse {
  _FakeDeleteModelResponse_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateModerationResponse_15 extends _i1.SmartFake
    implements _i3.CreateModerationResponse {
  _FakeCreateModerationResponse_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListAssistantsResponse_16 extends _i1.SmartFake
    implements _i3.ListAssistantsResponse {
  _FakeListAssistantsResponse_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAssistantObject_17 extends _i1.SmartFake
    implements _i3.AssistantObject {
  _FakeAssistantObject_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteAssistantResponse_18 extends _i1.SmartFake
    implements _i3.DeleteAssistantResponse {
  _FakeDeleteAssistantResponse_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeThreadObject_19 extends _i1.SmartFake implements _i3.ThreadObject {
  _FakeThreadObject_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteThreadResponse_20 extends _i1.SmartFake
    implements _i3.DeleteThreadResponse {
  _FakeDeleteThreadResponse_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListMessagesResponse_21 extends _i1.SmartFake
    implements _i3.ListMessagesResponse {
  _FakeListMessagesResponse_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMessageObject_22 extends _i1.SmartFake implements _i3.MessageObject {
  _FakeMessageObject_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteMessageResponse_23 extends _i1.SmartFake
    implements _i3.DeleteMessageResponse {
  _FakeDeleteMessageResponse_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRunObject_24 extends _i1.SmartFake implements _i3.RunObject {
  _FakeRunObject_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListRunsResponse_25 extends _i1.SmartFake
    implements _i3.ListRunsResponse {
  _FakeListRunsResponse_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListRunStepsResponse_26 extends _i1.SmartFake
    implements _i3.ListRunStepsResponse {
  _FakeListRunStepsResponse_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRunStepObject_27 extends _i1.SmartFake implements _i3.RunStepObject {
  _FakeRunStepObject_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListVectorStoresResponse_28 extends _i1.SmartFake
    implements _i3.ListVectorStoresResponse {
  _FakeListVectorStoresResponse_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVectorStoreObject_29 extends _i1.SmartFake
    implements _i3.VectorStoreObject {
  _FakeVectorStoreObject_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteVectorStoreResponse_30 extends _i1.SmartFake
    implements _i3.DeleteVectorStoreResponse {
  _FakeDeleteVectorStoreResponse_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListVectorStoreFilesResponse_31 extends _i1.SmartFake
    implements _i3.ListVectorStoreFilesResponse {
  _FakeListVectorStoreFilesResponse_31(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVectorStoreFileObject_32 extends _i1.SmartFake
    implements _i3.VectorStoreFileObject {
  _FakeVectorStoreFileObject_32(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteVectorStoreFileResponse_33 extends _i1.SmartFake
    implements _i3.DeleteVectorStoreFileResponse {
  _FakeDeleteVectorStoreFileResponse_33(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVectorStoreFileBatchObject_34 extends _i1.SmartFake
    implements _i3.VectorStoreFileBatchObject {
  _FakeVectorStoreFileBatchObject_34(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListBatchesResponse_35 extends _i1.SmartFake
    implements _i3.ListBatchesResponse {
  _FakeListBatchesResponse_35(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatch_36 extends _i1.SmartFake implements _i3.Batch {
  _FakeBatch_36(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OpenAIClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenAIClient extends _i1.Mock implements _i4.OpenAIClient {
  MockOpenAIClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiKey => (super.noSuchMethod(
        Invocation.getter(#apiKey),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#apiKey),
        ),
      ) as String);

  @override
  set apiKey(String? value) => super.noSuchMethod(
        Invocation.setter(
          #apiKey,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  Map<String, dynamic> get queryParams => (super.noSuchMethod(
        Invocation.getter(#queryParams),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);

  @override
  String get bearerToken => (super.noSuchMethod(
        Invocation.getter(#bearerToken),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#bearerToken),
        ),
      ) as String);

  @override
  set bearerToken(String? value) => super.noSuchMethod(
        Invocation.setter(
          #bearerToken,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Stream<_i3.CreateCompletionResponse> createCompletionStream(
          {required _i3.CreateCompletionRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCompletionStream,
          [],
          {#request: request},
        ),
        returnValue: _i6.Stream<_i3.CreateCompletionResponse>.empty(),
      ) as _i6.Stream<_i3.CreateCompletionResponse>);

  @override
  _i6.Stream<_i3.CreateChatCompletionStreamResponse> createChatCompletionStream(
          {required _i3.CreateChatCompletionRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createChatCompletionStream,
          [],
          {#request: request},
        ),
        returnValue: _i6.Stream<_i3.CreateChatCompletionStreamResponse>.empty(),
      ) as _i6.Stream<_i3.CreateChatCompletionStreamResponse>);

  @override
  _i6.Stream<_i3.AssistantStreamEvent> createThreadAndRunStream(
          {required _i3.CreateThreadAndRunRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createThreadAndRunStream,
          [],
          {#request: request},
        ),
        returnValue: _i6.Stream<_i3.AssistantStreamEvent>.empty(),
      ) as _i6.Stream<_i3.AssistantStreamEvent>);

  @override
  _i6.Stream<_i3.AssistantStreamEvent> createThreadRunStream({
    required String? threadId,
    required _i3.CreateRunRequest? request,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createThreadRunStream,
          [],
          {
            #threadId: threadId,
            #request: request,
          },
        ),
        returnValue: _i6.Stream<_i3.AssistantStreamEvent>.empty(),
      ) as _i6.Stream<_i3.AssistantStreamEvent>);

  @override
  _i6.Stream<_i3.AssistantStreamEvent> submitThreadToolOutputsToRunStream({
    required String? threadId,
    required String? runId,
    required _i3.SubmitToolOutputsRunRequest? request,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitThreadToolOutputsToRunStream,
          [],
          {
            #threadId: threadId,
            #runId: runId,
            #request: request,
          },
        ),
        returnValue: _i6.Stream<_i3.AssistantStreamEvent>.empty(),
      ) as _i6.Stream<_i3.AssistantStreamEvent>);

  @override
  _i6.Future<_i2.BaseRequest> onRequest(_i2.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #onRequest,
          [request],
        ),
        returnValue: _i6.Future<_i2.BaseRequest>.value(_FakeBaseRequest_1(
          this,
          Invocation.method(
            #onRequest,
            [request],
          ),
        )),
      ) as _i6.Future<_i2.BaseRequest>);

  @override
  void endSession() => super.noSuchMethod(
        Invocation.method(
          #endSession,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i2.StreamedResponse> onStreamedResponse(
          _i2.StreamedResponse? response) =>
      (super.noSuchMethod(
        Invocation.method(
          #onStreamedResponse,
          [response],
        ),
        returnValue:
            _i6.Future<_i2.StreamedResponse>.value(_FakeStreamedResponse_2(
          this,
          Invocation.method(
            #onStreamedResponse,
            [response],
          ),
        )),
      ) as _i6.Future<_i2.StreamedResponse>);

  @override
  _i6.Future<_i2.Response> onResponse(_i2.Response? response) =>
      (super.noSuchMethod(
        Invocation.method(
          #onResponse,
          [response],
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #onResponse,
            [response],
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.StreamedResponse> makeRequestStream({
    required String? baseUrl,
    required String? path,
    required _i7.HttpMethod? method,
    Map<String, dynamic>? queryParams = const {},
    Map<String, String>? headerParams = const {},
    bool? isMultipart = false,
    String? requestType = '',
    String? responseType = '',
    Object? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #makeRequestStream,
          [],
          {
            #baseUrl: baseUrl,
            #path: path,
            #method: method,
            #queryParams: queryParams,
            #headerParams: headerParams,
            #isMultipart: isMultipart,
            #requestType: requestType,
            #responseType: responseType,
            #body: body,
          },
        ),
        returnValue:
            _i6.Future<_i2.StreamedResponse>.value(_FakeStreamedResponse_2(
          this,
          Invocation.method(
            #makeRequestStream,
            [],
            {
              #baseUrl: baseUrl,
              #path: path,
              #method: method,
              #queryParams: queryParams,
              #headerParams: headerParams,
              #isMultipart: isMultipart,
              #requestType: requestType,
              #responseType: responseType,
              #body: body,
            },
          ),
        )),
      ) as _i6.Future<_i2.StreamedResponse>);

  @override
  _i6.Future<_i2.Response> makeRequest({
    required String? baseUrl,
    required String? path,
    required _i7.HttpMethod? method,
    Map<String, dynamic>? queryParams = const {},
    Map<String, String>? headerParams = const {},
    bool? isMultipart = false,
    String? requestType = '',
    String? responseType = '',
    Object? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #makeRequest,
          [],
          {
            #baseUrl: baseUrl,
            #path: path,
            #method: method,
            #queryParams: queryParams,
            #headerParams: headerParams,
            #isMultipart: isMultipart,
            #requestType: requestType,
            #responseType: responseType,
            #body: body,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #makeRequest,
            [],
            {
              #baseUrl: baseUrl,
              #path: path,
              #method: method,
              #queryParams: queryParams,
              #headerParams: headerParams,
              #isMultipart: isMultipart,
              #requestType: requestType,
              #responseType: responseType,
              #body: body,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i3.CreateChatCompletionResponse> createChatCompletion(
          {required _i3.CreateChatCompletionRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createChatCompletion,
          [],
          {#request: request},
        ),
        returnValue: _i6.Future<_i3.CreateChatCompletionResponse>.value(
            _FakeCreateChatCompletionResponse_4(
          this,
          Invocation.method(
            #createChatCompletion,
            [],
            {#request: request},
          ),
        )),
      ) as _i6.Future<_i3.CreateChatCompletionResponse>);

  @override
  _i6.Future<_i3.CreateCompletionResponse> createCompletion(
          {required _i3.CreateCompletionRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCompletion,
          [],
          {#request: request},
        ),
        returnValue: _i6.Future<_i3.CreateCompletionResponse>.value(
            _FakeCreateCompletionResponse_5(
          this,
          Invocation.method(
            #createCompletion,
            [],
            {#request: request},
          ),
        )),
      ) as _i6.Future<_i3.CreateCompletionResponse>);

  @override
  _i6.Future<_i3.CreateEmbeddingResponse> createEmbedding(
          {required _i3.CreateEmbeddingRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEmbedding,
          [],
          {#request: request},
        ),
        returnValue: _i6.Future<_i3.CreateEmbeddingResponse>.value(
            _FakeCreateEmbeddingResponse_6(
          this,
          Invocation.method(
            #createEmbedding,
            [],
            {#request: request},
          ),
        )),
      ) as _i6.Future<_i3.CreateEmbeddingResponse>);

  @override
  _i6.Future<_i3.ListPaginatedFineTuningJobsResponse>
      listPaginatedFineTuningJobs({
    String? after,
    int? limit = 20,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #listPaginatedFineTuningJobs,
              [],
              {
                #after: after,
                #limit: limit,
              },
            ),
            returnValue:
                _i6.Future<_i3.ListPaginatedFineTuningJobsResponse>.value(
                    _FakeListPaginatedFineTuningJobsResponse_7(
              this,
              Invocation.method(
                #listPaginatedFineTuningJobs,
                [],
                {
                  #after: after,
                  #limit: limit,
                },
              ),
            )),
          ) as _i6.Future<_i3.ListPaginatedFineTuningJobsResponse>);

  @override
  _i6.Future<_i3.FineTuningJob> createFineTuningJob(
          {required _i3.CreateFineTuningJobRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFineTuningJob,
          [],
          {#request: request},
        ),
        returnValue: _i6.Future<_i3.FineTuningJob>.value(_FakeFineTuningJob_8(
          this,
          Invocation.method(
            #createFineTuningJob,
            [],
            {#request: request},
          ),
        )),
      ) as _i6.Future<_i3.FineTuningJob>);

  @override
  _i6.Future<_i3.FineTuningJob> retrieveFineTuningJob(
          {required String? fineTuningJobId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #retrieveFineTuningJob,
          [],
          {#fineTuningJobId: fineTuningJobId},
        ),
        returnValue: _i6.Future<_i3.FineTuningJob>.value(_FakeFineTuningJob_8(
          this,
          Invocation.method(
            #retrieveFineTuningJob,
            [],
            {#fineTuningJobId: fineTuningJobId},
          ),
        )),
      ) as _i6.Future<_i3.FineTuningJob>);

  @override
  _i6.Future<_i3.ListFineTuningJobEventsResponse> listFineTuningEvents({
    required String? fineTuningJobId,
    String? after,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listFineTuningEvents,
          [],
          {
            #fineTuningJobId: fineTuningJobId,
            #after: after,
            #limit: limit,
          },
        ),
        returnValue: _i6.Future<_i3.ListFineTuningJobEventsResponse>.value(
            _FakeListFineTuningJobEventsResponse_9(
          this,
          Invocation.method(
            #listFineTuningEvents,
            [],
            {
              #fineTuningJobId: fineTuningJobId,
              #after: after,
              #limit: limit,
            },
          ),
        )),
      ) as _i6.Future<_i3.ListFineTuningJobEventsResponse>);

  @override
  _i6.Future<_i3.FineTuningJob> cancelFineTuningJob(
          {required String? fineTuningJobId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelFineTuningJob,
          [],
          {#fineTuningJobId: fineTuningJobId},
        ),
        returnValue: _i6.Future<_i3.FineTuningJob>.value(_FakeFineTuningJob_8(
          this,
          Invocation.method(
            #cancelFineTuningJob,
            [],
            {#fineTuningJobId: fineTuningJobId},
          ),
        )),
      ) as _i6.Future<_i3.FineTuningJob>);

  @override
  _i6.Future<_i3.ListFineTuningJobCheckpointsResponse>
      listFineTuningJobCheckpoints({
    required String? fineTuningJobId,
    String? after,
    int? limit = 10,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #listFineTuningJobCheckpoints,
              [],
              {
                #fineTuningJobId: fineTuningJobId,
                #after: after,
                #limit: limit,
              },
            ),
            returnValue:
                _i6.Future<_i3.ListFineTuningJobCheckpointsResponse>.value(
                    _FakeListFineTuningJobCheckpointsResponse_10(
              this,
              Invocation.method(
                #listFineTuningJobCheckpoints,
                [],
                {
                  #fineTuningJobId: fineTuningJobId,
                  #after: after,
                  #limit: limit,
                },
              ),
            )),
          ) as _i6.Future<_i3.ListFineTuningJobCheckpointsResponse>);

  @override
  _i6.Future<_i3.ImagesResponse> createImage(
          {required _i3.CreateImageRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createImage,
          [],
          {#request: request},
        ),
        returnValue:
            _i6.Future<_i3.ImagesResponse>.value(_FakeImagesResponse_11(
          this,
          Invocation.method(
            #createImage,
            [],
            {#request: request},
          ),
        )),
      ) as _i6.Future<_i3.ImagesResponse>);

  @override
  _i6.Future<_i3.ListModelsResponse> listModels() => (super.noSuchMethod(
        Invocation.method(
          #listModels,
          [],
        ),
        returnValue:
            _i6.Future<_i3.ListModelsResponse>.value(_FakeListModelsResponse_12(
          this,
          Invocation.method(
            #listModels,
            [],
          ),
        )),
      ) as _i6.Future<_i3.ListModelsResponse>);

  @override
  _i6.Future<_i3.Model> retrieveModel({required String? model}) =>
      (super.noSuchMethod(
        Invocation.method(
          #retrieveModel,
          [],
          {#model: model},
        ),
        returnValue: _i6.Future<_i3.Model>.value(_FakeModel_13(
          this,
          Invocation.method(
            #retrieveModel,
            [],
            {#model: model},
          ),
        )),
      ) as _i6.Future<_i3.Model>);

  @override
  _i6.Future<_i3.DeleteModelResponse> deleteModel({required String? model}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteModel,
          [],
          {#model: model},
        ),
        returnValue: _i6.Future<_i3.DeleteModelResponse>.value(
            _FakeDeleteModelResponse_14(
          this,
          Invocation.method(
            #deleteModel,
            [],
            {#model: model},
          ),
        )),
      ) as _i6.Future<_i3.DeleteModelResponse>);

  @override
  _i6.Future<_i3.CreateModerationResponse> createModeration(
          {required _i3.CreateModerationRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createModeration,
          [],
          {#request: request},
        ),
        returnValue: _i6.Future<_i3.CreateModerationResponse>.value(
            _FakeCreateModerationResponse_15(
          this,
          Invocation.method(
            #createModeration,
            [],
            {#request: request},
          ),
        )),
      ) as _i6.Future<_i3.CreateModerationResponse>);

  @override
  _i6.Future<_i3.ListAssistantsResponse> listAssistants({
    int? limit = 20,
    String? order = 'desc',
    String? after,
    String? before,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listAssistants,
          [],
          {
            #limit: limit,
            #order: order,
            #after: after,
            #before: before,
          },
        ),
        returnValue: _i6.Future<_i3.ListAssistantsResponse>.value(
            _FakeListAssistantsResponse_16(
          this,
          Invocation.method(
            #listAssistants,
            [],
            {
              #limit: limit,
              #order: order,
              #after: after,
              #before: before,
            },
          ),
        )),
      ) as _i6.Future<_i3.ListAssistantsResponse>);

  @override
  _i6.Future<_i3.AssistantObject> createAssistant(
          {required _i3.CreateAssistantRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAssistant,
          [],
          {#request: request},
        ),
        returnValue:
            _i6.Future<_i3.AssistantObject>.value(_FakeAssistantObject_17(
          this,
          Invocation.method(
            #createAssistant,
            [],
            {#request: request},
          ),
        )),
      ) as _i6.Future<_i3.AssistantObject>);

  @override
  _i6.Future<_i3.AssistantObject> getAssistant(
          {required String? assistantId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssistant,
          [],
          {#assistantId: assistantId},
        ),
        returnValue:
            _i6.Future<_i3.AssistantObject>.value(_FakeAssistantObject_17(
          this,
          Invocation.method(
            #getAssistant,
            [],
            {#assistantId: assistantId},
          ),
        )),
      ) as _i6.Future<_i3.AssistantObject>);

  @override
  _i6.Future<_i3.AssistantObject> modifyAssistant({
    required String? assistantId,
    required _i3.ModifyAssistantRequest? request,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modifyAssistant,
          [],
          {
            #assistantId: assistantId,
            #request: request,
          },
        ),
        returnValue:
            _i6.Future<_i3.AssistantObject>.value(_FakeAssistantObject_17(
          this,
          Invocation.method(
            #modifyAssistant,
            [],
            {
              #assistantId: assistantId,
              #request: request,
            },
          ),
        )),
      ) as _i6.Future<_i3.AssistantObject>);

  @override
  _i6.Future<_i3.DeleteAssistantResponse> deleteAssistant(
          {required String? assistantId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAssistant,
          [],
          {#assistantId: assistantId},
        ),
        returnValue: _i6.Future<_i3.DeleteAssistantResponse>.value(
            _FakeDeleteAssistantResponse_18(
          this,
          Invocation.method(
            #deleteAssistant,
            [],
            {#assistantId: assistantId},
          ),
        )),
      ) as _i6.Future<_i3.DeleteAssistantResponse>);

  @override
  _i6.Future<_i3.ThreadObject> createThread(
          {_i3.CreateThreadRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createThread,
          [],
          {#request: request},
        ),
        returnValue: _i6.Future<_i3.ThreadObject>.value(_FakeThreadObject_19(
          this,
          Invocation.method(
            #createThread,
            [],
            {#request: request},
          ),
        )),
      ) as _i6.Future<_i3.ThreadObject>);

  @override
  _i6.Future<_i3.ThreadObject> getThread({required String? threadId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getThread,
          [],
          {#threadId: threadId},
        ),
        returnValue: _i6.Future<_i3.ThreadObject>.value(_FakeThreadObject_19(
          this,
          Invocation.method(
            #getThread,
            [],
            {#threadId: threadId},
          ),
        )),
      ) as _i6.Future<_i3.ThreadObject>);

  @override
  _i6.Future<_i3.ThreadObject> modifyThread({
    required String? threadId,
    required _i3.ModifyThreadRequest? request,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modifyThread,
          [],
          {
            #threadId: threadId,
            #request: request,
          },
        ),
        returnValue: _i6.Future<_i3.ThreadObject>.value(_FakeThreadObject_19(
          this,
          Invocation.method(
            #modifyThread,
            [],
            {
              #threadId: threadId,
              #request: request,
            },
          ),
        )),
      ) as _i6.Future<_i3.ThreadObject>);

  @override
  _i6.Future<_i3.DeleteThreadResponse> deleteThread(
          {required String? threadId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteThread,
          [],
          {#threadId: threadId},
        ),
        returnValue: _i6.Future<_i3.DeleteThreadResponse>.value(
            _FakeDeleteThreadResponse_20(
          this,
          Invocation.method(
            #deleteThread,
            [],
            {#threadId: threadId},
          ),
        )),
      ) as _i6.Future<_i3.DeleteThreadResponse>);

  @override
  _i6.Future<_i3.ListMessagesResponse> listThreadMessages({
    required String? threadId,
    int? limit = 20,
    String? order = 'desc',
    String? after,
    String? before,
    String? runId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listThreadMessages,
          [],
          {
            #threadId: threadId,
            #limit: limit,
            #order: order,
            #after: after,
            #before: before,
            #runId: runId,
          },
        ),
        returnValue: _i6.Future<_i3.ListMessagesResponse>.value(
            _FakeListMessagesResponse_21(
          this,
          Invocation.method(
            #listThreadMessages,
            [],
            {
              #threadId: threadId,
              #limit: limit,
              #order: order,
              #after: after,
              #before: before,
              #runId: runId,
            },
          ),
        )),
      ) as _i6.Future<_i3.ListMessagesResponse>);

  @override
  _i6.Future<_i3.MessageObject> createThreadMessage({
    required String? threadId,
    required _i3.CreateMessageRequest? request,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createThreadMessage,
          [],
          {
            #threadId: threadId,
            #request: request,
          },
        ),
        returnValue: _i6.Future<_i3.MessageObject>.value(_FakeMessageObject_22(
          this,
          Invocation.method(
            #createThreadMessage,
            [],
            {
              #threadId: threadId,
              #request: request,
            },
          ),
        )),
      ) as _i6.Future<_i3.MessageObject>);

  @override
  _i6.Future<_i3.MessageObject> getThreadMessage({
    required String? threadId,
    required String? messageId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getThreadMessage,
          [],
          {
            #threadId: threadId,
            #messageId: messageId,
          },
        ),
        returnValue: _i6.Future<_i3.MessageObject>.value(_FakeMessageObject_22(
          this,
          Invocation.method(
            #getThreadMessage,
            [],
            {
              #threadId: threadId,
              #messageId: messageId,
            },
          ),
        )),
      ) as _i6.Future<_i3.MessageObject>);

  @override
  _i6.Future<_i3.MessageObject> modifyThreadMessage({
    required String? threadId,
    required String? messageId,
    required _i3.ModifyMessageRequest? request,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modifyThreadMessage,
          [],
          {
            #threadId: threadId,
            #messageId: messageId,
            #request: request,
          },
        ),
        returnValue: _i6.Future<_i3.MessageObject>.value(_FakeMessageObject_22(
          this,
          Invocation.method(
            #modifyThreadMessage,
            [],
            {
              #threadId: threadId,
              #messageId: messageId,
              #request: request,
            },
          ),
        )),
      ) as _i6.Future<_i3.MessageObject>);

  @override
  _i6.Future<_i3.DeleteMessageResponse> deleteThreadMessage({
    required String? threadId,
    required String? messageId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteThreadMessage,
          [],
          {
            #threadId: threadId,
            #messageId: messageId,
          },
        ),
        returnValue: _i6.Future<_i3.DeleteMessageResponse>.value(
            _FakeDeleteMessageResponse_23(
          this,
          Invocation.method(
            #deleteThreadMessage,
            [],
            {
              #threadId: threadId,
              #messageId: messageId,
            },
          ),
        )),
      ) as _i6.Future<_i3.DeleteMessageResponse>);

  @override
  _i6.Future<_i3.RunObject> createThreadAndRun(
          {required _i3.CreateThreadAndRunRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createThreadAndRun,
          [],
          {#request: request},
        ),
        returnValue: _i6.Future<_i3.RunObject>.value(_FakeRunObject_24(
          this,
          Invocation.method(
            #createThreadAndRun,
            [],
            {#request: request},
          ),
        )),
      ) as _i6.Future<_i3.RunObject>);

  @override
  _i6.Future<_i3.ListRunsResponse> listThreadRuns({
    required String? threadId,
    int? limit = 20,
    String? order = 'desc',
    String? after,
    String? before,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listThreadRuns,
          [],
          {
            #threadId: threadId,
            #limit: limit,
            #order: order,
            #after: after,
            #before: before,
          },
        ),
        returnValue:
            _i6.Future<_i3.ListRunsResponse>.value(_FakeListRunsResponse_25(
          this,
          Invocation.method(
            #listThreadRuns,
            [],
            {
              #threadId: threadId,
              #limit: limit,
              #order: order,
              #after: after,
              #before: before,
            },
          ),
        )),
      ) as _i6.Future<_i3.ListRunsResponse>);

  @override
  _i6.Future<_i3.RunObject> createThreadRun({
    required String? threadId,
    String? include,
    required _i3.CreateRunRequest? request,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createThreadRun,
          [],
          {
            #threadId: threadId,
            #include: include,
            #request: request,
          },
        ),
        returnValue: _i6.Future<_i3.RunObject>.value(_FakeRunObject_24(
          this,
          Invocation.method(
            #createThreadRun,
            [],
            {
              #threadId: threadId,
              #include: include,
              #request: request,
            },
          ),
        )),
      ) as _i6.Future<_i3.RunObject>);

  @override
  _i6.Future<_i3.RunObject> getThreadRun({
    required String? threadId,
    required String? runId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getThreadRun,
          [],
          {
            #threadId: threadId,
            #runId: runId,
          },
        ),
        returnValue: _i6.Future<_i3.RunObject>.value(_FakeRunObject_24(
          this,
          Invocation.method(
            #getThreadRun,
            [],
            {
              #threadId: threadId,
              #runId: runId,
            },
          ),
        )),
      ) as _i6.Future<_i3.RunObject>);

  @override
  _i6.Future<_i3.RunObject> modifyThreadRun({
    required String? threadId,
    required String? runId,
    required _i3.ModifyRunRequest? request,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modifyThreadRun,
          [],
          {
            #threadId: threadId,
            #runId: runId,
            #request: request,
          },
        ),
        returnValue: _i6.Future<_i3.RunObject>.value(_FakeRunObject_24(
          this,
          Invocation.method(
            #modifyThreadRun,
            [],
            {
              #threadId: threadId,
              #runId: runId,
              #request: request,
            },
          ),
        )),
      ) as _i6.Future<_i3.RunObject>);

  @override
  _i6.Future<_i3.RunObject> submitThreadToolOutputsToRun({
    required String? threadId,
    required String? runId,
    required _i3.SubmitToolOutputsRunRequest? request,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitThreadToolOutputsToRun,
          [],
          {
            #threadId: threadId,
            #runId: runId,
            #request: request,
          },
        ),
        returnValue: _i6.Future<_i3.RunObject>.value(_FakeRunObject_24(
          this,
          Invocation.method(
            #submitThreadToolOutputsToRun,
            [],
            {
              #threadId: threadId,
              #runId: runId,
              #request: request,
            },
          ),
        )),
      ) as _i6.Future<_i3.RunObject>);

  @override
  _i6.Future<_i3.RunObject> cancelThreadRun({
    required String? threadId,
    required String? runId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelThreadRun,
          [],
          {
            #threadId: threadId,
            #runId: runId,
          },
        ),
        returnValue: _i6.Future<_i3.RunObject>.value(_FakeRunObject_24(
          this,
          Invocation.method(
            #cancelThreadRun,
            [],
            {
              #threadId: threadId,
              #runId: runId,
            },
          ),
        )),
      ) as _i6.Future<_i3.RunObject>);

  @override
  _i6.Future<_i3.ListRunStepsResponse> listThreadRunSteps({
    required String? threadId,
    required String? runId,
    int? limit = 20,
    String? order = 'desc',
    String? after,
    String? before,
    String? include,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listThreadRunSteps,
          [],
          {
            #threadId: threadId,
            #runId: runId,
            #limit: limit,
            #order: order,
            #after: after,
            #before: before,
            #include: include,
          },
        ),
        returnValue: _i6.Future<_i3.ListRunStepsResponse>.value(
            _FakeListRunStepsResponse_26(
          this,
          Invocation.method(
            #listThreadRunSteps,
            [],
            {
              #threadId: threadId,
              #runId: runId,
              #limit: limit,
              #order: order,
              #after: after,
              #before: before,
              #include: include,
            },
          ),
        )),
      ) as _i6.Future<_i3.ListRunStepsResponse>);

  @override
  _i6.Future<_i3.RunStepObject> getThreadRunStep({
    required String? threadId,
    required String? runId,
    required String? stepId,
    String? include,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getThreadRunStep,
          [],
          {
            #threadId: threadId,
            #runId: runId,
            #stepId: stepId,
            #include: include,
          },
        ),
        returnValue: _i6.Future<_i3.RunStepObject>.value(_FakeRunStepObject_27(
          this,
          Invocation.method(
            #getThreadRunStep,
            [],
            {
              #threadId: threadId,
              #runId: runId,
              #stepId: stepId,
              #include: include,
            },
          ),
        )),
      ) as _i6.Future<_i3.RunStepObject>);

  @override
  _i6.Future<_i3.ListVectorStoresResponse> listVectorStores({
    int? limit = 20,
    String? order = 'desc',
    String? after,
    String? before,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listVectorStores,
          [],
          {
            #limit: limit,
            #order: order,
            #after: after,
            #before: before,
          },
        ),
        returnValue: _i6.Future<_i3.ListVectorStoresResponse>.value(
            _FakeListVectorStoresResponse_28(
          this,
          Invocation.method(
            #listVectorStores,
            [],
            {
              #limit: limit,
              #order: order,
              #after: after,
              #before: before,
            },
          ),
        )),
      ) as _i6.Future<_i3.ListVectorStoresResponse>);

  @override
  _i6.Future<_i3.VectorStoreObject> createVectorStore(
          {required _i3.CreateVectorStoreRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createVectorStore,
          [],
          {#request: request},
        ),
        returnValue:
            _i6.Future<_i3.VectorStoreObject>.value(_FakeVectorStoreObject_29(
          this,
          Invocation.method(
            #createVectorStore,
            [],
            {#request: request},
          ),
        )),
      ) as _i6.Future<_i3.VectorStoreObject>);

  @override
  _i6.Future<_i3.VectorStoreObject> getVectorStore(
          {required String? vectorStoreId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVectorStore,
          [],
          {#vectorStoreId: vectorStoreId},
        ),
        returnValue:
            _i6.Future<_i3.VectorStoreObject>.value(_FakeVectorStoreObject_29(
          this,
          Invocation.method(
            #getVectorStore,
            [],
            {#vectorStoreId: vectorStoreId},
          ),
        )),
      ) as _i6.Future<_i3.VectorStoreObject>);

  @override
  _i6.Future<_i3.VectorStoreObject> modifyVectorStore({
    required String? vectorStoreId,
    required _i3.UpdateVectorStoreRequest? request,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modifyVectorStore,
          [],
          {
            #vectorStoreId: vectorStoreId,
            #request: request,
          },
        ),
        returnValue:
            _i6.Future<_i3.VectorStoreObject>.value(_FakeVectorStoreObject_29(
          this,
          Invocation.method(
            #modifyVectorStore,
            [],
            {
              #vectorStoreId: vectorStoreId,
              #request: request,
            },
          ),
        )),
      ) as _i6.Future<_i3.VectorStoreObject>);

  @override
  _i6.Future<_i3.DeleteVectorStoreResponse> deleteVectorStore(
          {required String? vectorStoreId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVectorStore,
          [],
          {#vectorStoreId: vectorStoreId},
        ),
        returnValue: _i6.Future<_i3.DeleteVectorStoreResponse>.value(
            _FakeDeleteVectorStoreResponse_30(
          this,
          Invocation.method(
            #deleteVectorStore,
            [],
            {#vectorStoreId: vectorStoreId},
          ),
        )),
      ) as _i6.Future<_i3.DeleteVectorStoreResponse>);

  @override
  _i6.Future<_i3.ListVectorStoreFilesResponse> listVectorStoreFiles({
    required String? vectorStoreId,
    int? limit = 20,
    String? order = 'desc',
    String? after,
    String? before,
    String? filter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listVectorStoreFiles,
          [],
          {
            #vectorStoreId: vectorStoreId,
            #limit: limit,
            #order: order,
            #after: after,
            #before: before,
            #filter: filter,
          },
        ),
        returnValue: _i6.Future<_i3.ListVectorStoreFilesResponse>.value(
            _FakeListVectorStoreFilesResponse_31(
          this,
          Invocation.method(
            #listVectorStoreFiles,
            [],
            {
              #vectorStoreId: vectorStoreId,
              #limit: limit,
              #order: order,
              #after: after,
              #before: before,
              #filter: filter,
            },
          ),
        )),
      ) as _i6.Future<_i3.ListVectorStoreFilesResponse>);

  @override
  _i6.Future<_i3.VectorStoreFileObject> createVectorStoreFile({
    required String? vectorStoreId,
    required _i3.CreateVectorStoreFileRequest? request,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createVectorStoreFile,
          [],
          {
            #vectorStoreId: vectorStoreId,
            #request: request,
          },
        ),
        returnValue: _i6.Future<_i3.VectorStoreFileObject>.value(
            _FakeVectorStoreFileObject_32(
          this,
          Invocation.method(
            #createVectorStoreFile,
            [],
            {
              #vectorStoreId: vectorStoreId,
              #request: request,
            },
          ),
        )),
      ) as _i6.Future<_i3.VectorStoreFileObject>);

  @override
  _i6.Future<_i3.VectorStoreFileObject> getVectorStoreFile({
    required String? vectorStoreId,
    required String? fileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVectorStoreFile,
          [],
          {
            #vectorStoreId: vectorStoreId,
            #fileId: fileId,
          },
        ),
        returnValue: _i6.Future<_i3.VectorStoreFileObject>.value(
            _FakeVectorStoreFileObject_32(
          this,
          Invocation.method(
            #getVectorStoreFile,
            [],
            {
              #vectorStoreId: vectorStoreId,
              #fileId: fileId,
            },
          ),
        )),
      ) as _i6.Future<_i3.VectorStoreFileObject>);

  @override
  _i6.Future<_i3.DeleteVectorStoreFileResponse> deleteVectorStoreFile({
    required String? vectorStoreId,
    required String? fileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVectorStoreFile,
          [],
          {
            #vectorStoreId: vectorStoreId,
            #fileId: fileId,
          },
        ),
        returnValue: _i6.Future<_i3.DeleteVectorStoreFileResponse>.value(
            _FakeDeleteVectorStoreFileResponse_33(
          this,
          Invocation.method(
            #deleteVectorStoreFile,
            [],
            {
              #vectorStoreId: vectorStoreId,
              #fileId: fileId,
            },
          ),
        )),
      ) as _i6.Future<_i3.DeleteVectorStoreFileResponse>);

  @override
  _i6.Future<_i3.VectorStoreFileBatchObject> createVectorStoreFileBatch({
    required String? vectorStoreId,
    required _i3.CreateVectorStoreFileBatchRequest? request,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createVectorStoreFileBatch,
          [],
          {
            #vectorStoreId: vectorStoreId,
            #request: request,
          },
        ),
        returnValue: _i6.Future<_i3.VectorStoreFileBatchObject>.value(
            _FakeVectorStoreFileBatchObject_34(
          this,
          Invocation.method(
            #createVectorStoreFileBatch,
            [],
            {
              #vectorStoreId: vectorStoreId,
              #request: request,
            },
          ),
        )),
      ) as _i6.Future<_i3.VectorStoreFileBatchObject>);

  @override
  _i6.Future<_i3.VectorStoreFileBatchObject> getVectorStoreFileBatch({
    required String? vectorStoreId,
    required String? batchId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVectorStoreFileBatch,
          [],
          {
            #vectorStoreId: vectorStoreId,
            #batchId: batchId,
          },
        ),
        returnValue: _i6.Future<_i3.VectorStoreFileBatchObject>.value(
            _FakeVectorStoreFileBatchObject_34(
          this,
          Invocation.method(
            #getVectorStoreFileBatch,
            [],
            {
              #vectorStoreId: vectorStoreId,
              #batchId: batchId,
            },
          ),
        )),
      ) as _i6.Future<_i3.VectorStoreFileBatchObject>);

  @override
  _i6.Future<_i3.VectorStoreFileBatchObject> cancelVectorStoreFileBatch({
    required String? vectorStoreId,
    required String? batchId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelVectorStoreFileBatch,
          [],
          {
            #vectorStoreId: vectorStoreId,
            #batchId: batchId,
          },
        ),
        returnValue: _i6.Future<_i3.VectorStoreFileBatchObject>.value(
            _FakeVectorStoreFileBatchObject_34(
          this,
          Invocation.method(
            #cancelVectorStoreFileBatch,
            [],
            {
              #vectorStoreId: vectorStoreId,
              #batchId: batchId,
            },
          ),
        )),
      ) as _i6.Future<_i3.VectorStoreFileBatchObject>);

  @override
  _i6.Future<_i3.ListVectorStoreFilesResponse> listFilesInVectorStoreBatch({
    required String? vectorStoreId,
    required String? batchId,
    int? limit = 20,
    String? order = 'desc',
    String? after,
    String? before,
    String? filter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listFilesInVectorStoreBatch,
          [],
          {
            #vectorStoreId: vectorStoreId,
            #batchId: batchId,
            #limit: limit,
            #order: order,
            #after: after,
            #before: before,
            #filter: filter,
          },
        ),
        returnValue: _i6.Future<_i3.ListVectorStoreFilesResponse>.value(
            _FakeListVectorStoreFilesResponse_31(
          this,
          Invocation.method(
            #listFilesInVectorStoreBatch,
            [],
            {
              #vectorStoreId: vectorStoreId,
              #batchId: batchId,
              #limit: limit,
              #order: order,
              #after: after,
              #before: before,
              #filter: filter,
            },
          ),
        )),
      ) as _i6.Future<_i3.ListVectorStoreFilesResponse>);

  @override
  _i6.Future<_i3.ListBatchesResponse> listBatches({
    String? after,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listBatches,
          [],
          {
            #after: after,
            #limit: limit,
          },
        ),
        returnValue: _i6.Future<_i3.ListBatchesResponse>.value(
            _FakeListBatchesResponse_35(
          this,
          Invocation.method(
            #listBatches,
            [],
            {
              #after: after,
              #limit: limit,
            },
          ),
        )),
      ) as _i6.Future<_i3.ListBatchesResponse>);

  @override
  _i6.Future<_i3.Batch> createBatch(
          {required _i3.CreateBatchRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBatch,
          [],
          {#request: request},
        ),
        returnValue: _i6.Future<_i3.Batch>.value(_FakeBatch_36(
          this,
          Invocation.method(
            #createBatch,
            [],
            {#request: request},
          ),
        )),
      ) as _i6.Future<_i3.Batch>);

  @override
  _i6.Future<_i3.Batch> retrieveBatch({required String? batchId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #retrieveBatch,
          [],
          {#batchId: batchId},
        ),
        returnValue: _i6.Future<_i3.Batch>.value(_FakeBatch_36(
          this,
          Invocation.method(
            #retrieveBatch,
            [],
            {#batchId: batchId},
          ),
        )),
      ) as _i6.Future<_i3.Batch>);

  @override
  _i6.Future<_i3.Batch> cancelBatch({required String? batchId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelBatch,
          [],
          {#batchId: batchId},
        ),
        returnValue: _i6.Future<_i3.Batch>.value(_FakeBatch_36(
          this,
          Invocation.method(
            #cancelBatch,
            [],
            {#batchId: batchId},
          ),
        )),
      ) as _i6.Future<_i3.Batch>);
}
